### ISSUE TITLE
Dark mode: orange or dark blue?

### ISSUE THREAD

**Issue by nao-l** [nao-l/ScratchTutorials#2]
I was finishing the last -- important -- details of the ui when I verified the dark mode, and the I suddenly had idea of putting orange instead of dark blue as the primary color. So I let you decide of this, maybe @Scratchinax, because you have more skills than me with the designs. 
You can answer 1 for the dark blue, and 2 for the orange.

![D54FEFF5-3756-4F4B-B25C-186FB9519EA8](https://user-images.githubusercontent.com/98713994/161354073-aab3b7da-1148-4e7b-b692-2f712c0758e2.png)

![4F386314-6DC7-4643-9DE6-0988FE1FB287](https://user-images.githubusercontent.com/98713994/161354078-44fef3ad-babb-4622-920e-cb02722ad197.png)

**Comment by Scratchinax** [comment]
I think you should keep the Dark Blue as the primary color, because the Orange don’t matches with the light mode primary color.
